In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

In [108]:
all_patients = pd.read_excel("../../New_Extra_Data/CRLM_Status_230622.xlsx")
all_scans = pd.read_excel("../../New_Extra_Data/combination_archive_with_dates.xlsx")
existed_patients = pd.read_excel("../../New_Extra_Data/Imaging log HGP CRLM CTs - Version2.xls",skiprows=4)

In [4]:
#get all patients id
all_patients_id = all_patients["PID"].tolist()

#get existed patients id
existed_patients_id = existed_patients["PID"].tolist()

#get missing patients id
missing_patients_id = list(set(all_patients_id) - set(existed_patients_id))

#IDs that don't have scan
missing_patients_id_no_scan = list(set(all_patients_id)-set(all_scans["PID Lokaal"].unique().tolist()))

# IDs that possible have appropriate scan
possible_missing_patients_id = list(set(missing_patients_id)-set(missing_patients_id_no_scan))

In [86]:
all_scans

,Unnamed: 0.1,Unnamed: 0,Identificatienummer patïent,Accessionnummer,PID Lokaal,Datum,Beschrijving,Mod.,# Beelden,BIRADS=0 (10),Tijd,Lichaamsdeel,Status,Subspecialiteit (5),Date of detection CRLM,Date of resection CRLM
0,0,0,797177,5405410.02,797177,2015-01-02,HERBEOORDELING CT THORAX ABDOMEN,CT,500,N,11:54:32,HABD,Gelezen,ABDOMEN,02.01.2015,16.04.2015
1,1,1,797177,5432391.02,797177,2015-03-19,CT Thorax/abdomen,CT OT,836,N,15:15:00,ABDO,Gelezen,ABDOMEN,02.01.2015,16.04.2015
2,2,2,308469,3682686.01,308469,2007-03-19,COMBI CT - THORAX - B.O.BUIK - M.C. DUMMY TBV ...,CT PR,198,N,14:44:09,ABDO,Gelezen,ABDOMEN,02.08.2006,12.10.2006
3,3,3,308469,3707183.02,308469,2007-06-05,CT lever multifase,CT PR,172,N,09:18:47,ABDO,Gelezen,ABDOMEN,02.08.2006,12.10.2006
4,4,4,308469,3750218.02,308469,2007-09-27,CT COMBI THORAX EN ABDOMEN ALGEMEEN,CT PR,208,N,10:44:41,THX,Gelezen,THORAX,02.08.2006,12.10.2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5004,5004,5009,9731939,5291250.02,9731939,2014-10-27,CT Thorax/abdomen,CT OT,923,N,16:15:00,ABDO,Gelezen,ABDOMEN,18.02.2014,23.04.2014
5005,5005,5010,9950266,3669084.01,9950266,2007-02-08,COMBI CT - B.BUIK - O.BUIK - M.C. DUMMY TBV RO...,CT PR,108,N,14:14:58,ABDO,Gelezen,ABDOMEN,15.04.2002,07.08.2002
5006,5006,5011,9950266,3679675.01,9950266,2007-02-28,COMBI CT - B.BUIK - O.BUIK - M.C. DUMMY TBV RO...,CT PR,96,N,13:43:15,ABDO,Gelezen,ABDOMEN,15.04.2002,07.08.2002
5007,5007,5012,9950266,3682188.01,9950266,2007-03-08,COMBI CT - PUNCT. - CT THORAX - Z.C. DUMMY TBV...,CT PR,61,N,14:16:37,THX,Gelezen,INTERVENTI,15.04.2002,07.08.2002
5008,5008,5013,9950266,3725501.02,9950266,2007-06-12,COMBI CT - THORAX - B.O.BUIK - M.C. DUMMY TBV ...,CT PR,353,N,10:03:53,ABDO,Gelezen,ABDOMEN,15.04.2002,07.08.2002

## finding avaiable scans

In [107]:
all_scans

,Unnamed: 0.1,Unnamed: 0,Identificatienummer patïent,Accessionnummer,PID Lokaal,Datum,Beschrijving,Mod.,# Beelden,BIRADS=0 (10),Tijd,Lichaamsdeel,Status,Subspecialiteit (5),Date of detection CRLM,Date of resection CRLM
0,0,0,797177,5405410.02,797177,2015-01-02,HERBEOORDELING CT THORAX ABDOMEN,CT,500,N,11:54:32,HABD,Gelezen,ABDOMEN,2015-01-02,2015-01-02
1,1,1,797177,5432391.02,797177,2015-03-19,CT Thorax/abdomen,CT OT,836,N,15:15:00,ABDO,Gelezen,ABDOMEN,2015-01-02,2015-01-02
2,2,2,308469,3682686.01,308469,2007-03-19,COMBI CT - THORAX - B.O.BUIK - M.C. DUMMY TBV ...,CT PR,198,N,14:44:09,ABDO,Gelezen,ABDOMEN,2006-08-02,2006-08-02
3,3,3,308469,3707183.02,308469,2007-06-05,CT lever multifase,CT PR,172,N,09:18:47,ABDO,Gelezen,ABDOMEN,2006-08-02,2006-08-02
4,4,4,308469,3750218.02,308469,2007-09-27,CT COMBI THORAX EN ABDOMEN ALGEMEEN,CT PR,208,N,10:44:41,THX,Gelezen,THORAX,2006-08-02,2006-08-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5004,5004,5009,9731939,5291250.02,9731939,2014-10-27,CT Thorax/abdomen,CT OT,923,N,16:15:00,ABDO,Gelezen,ABDOMEN,2014-02-18,2014-02-18
5005,5005,5010,9950266,3669084.01,9950266,2007-02-08,COMBI CT - B.BUIK - O.BUIK - M.C. DUMMY TBV RO...,CT PR,108,N,14:14:58,ABDO,Gelezen,ABDOMEN,2002-04-15,2002-04-15
5006,5006,5011,9950266,3679675.01,9950266,2007-02-28,COMBI CT - B.BUIK - O.BUIK - M.C. DUMMY TBV RO...,CT PR,96,N,13:43:15,ABDO,Gelezen,ABDOMEN,2002-04-15,2002-04-15
5007,5007,5012,9950266,3682188.01,9950266,2007-03-08,COMBI CT - PUNCT. - CT THORAX - Z.C. DUMMY TBV...,CT PR,61,N,14:16:37,THX,Gelezen,INTERVENTI,2002-04-15,2002-04-15
5008,5008,5013,9950266,3725501.02,9950266,2007-06-12,COMBI CT - THORAX - B.O.BUIK - M.C. DUMMY TBV ...,CT PR,353,N,10:03:53,ABDO,Gelezen,ABDOMEN,2002-04-15,2002-04-15

In [105]:
all_scans['Date of detection CRLM'] = pd.to_datetime(all_scans['Date of detection CRLM'], format="%d.%m.%Y")

,Unnamed: 0.1,Unnamed: 0,Identificatienummer patïent,Accessionnummer,PID Lokaal,Datum,Beschrijving,Mod.,# Beelden,BIRADS=0 (10),Tijd,Lichaamsdeel,Status,Subspecialiteit (5),Date of detection CRLM,Date of resection CRLM
0,0,0,797177,5405410.02,797177,2015-01-02,HERBEOORDELING CT THORAX ABDOMEN,CT,500,N,11:54:32,HABD,Gelezen,ABDOMEN,2015-01-02,16.04.2015
1,1,1,797177,5432391.02,797177,2015-03-19,CT Thorax/abdomen,CT OT,836,N,15:15:00,ABDO,Gelezen,ABDOMEN,2015-01-02,16.04.2015
2,2,2,308469,3682686.01,308469,2007-03-19,COMBI CT - THORAX - B.O.BUIK - M.C. DUMMY TBV ...,CT PR,198,N,14:44:09,ABDO,Gelezen,ABDOMEN,2006-08-02,12.10.2006
3,3,3,308469,3707183.02,308469,2007-06-05,CT lever multifase,CT PR,172,N,09:18:47,ABDO,Gelezen,ABDOMEN,2006-08-02,12.10.2006
4,4,4,308469,3750218.02,308469,2007-09-27,CT COMBI THORAX EN ABDOMEN ALGEMEEN,CT PR,208,N,10:44:41,THX,Gelezen,THORAX,2006-08-02,12.10.2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5004,5004,5009,9731939,5291250.02,9731939,2014-10-27,CT Thorax/abdomen,CT OT,923,N,16:15:00,ABDO,Gelezen,ABDOMEN,2014-02-18,23.04.2014
5005,5005,5010,9950266,3669084.01,9950266,2007-02-08,COMBI CT - B.BUIK - O.BUIK - M.C. DUMMY TBV RO...,CT PR,108,N,14:14:58,ABDO,Gelezen,ABDOMEN,2002-04-15,07.08.2002
5006,5006,5011,9950266,3679675.01,9950266,2007-02-28,COMBI CT - B.BUIK - O.BUIK - M.C. DUMMY TBV RO...,CT PR,96,N,13:43:15,ABDO,Gelezen,ABDOMEN,2002-04-15,07.08.2002
5007,5007,5012,9950266,3682188.01,9950266,2007-03-08,COMBI CT - PUNCT. - CT THORAX - Z.C. DUMMY TBV...,CT PR,61,N,14:16:37,THX,Gelezen,INTERVENTI,2002-04-15,07.08.2002
5008,5008,5013,9950266,3725501.02,9950266,2007-06-12,COMBI CT - THORAX - B.O.BUIK - M.C. DUMMY TBV ...,CT PR,353,N,10:03:53,ABDO,Gelezen,ABDOMEN,2002-04-15,07.08.2002

In [109]:
all_scans['Datum'] = pd.to_datetime(all_scans['Datum'],format=("%Y-%m-%d"))
all_scans['Date of detection CRLM'] = pd.to_datetime(all_scans['Date of detection CRLM'],format=("%d.%m.%Y"))
all_scans['Date of resection CRLM'] = pd.to_datetime(all_scans['Date of resection CRLM'],format=("%d.%m.%Y"))
all_scans['Date_In_Range'] = all_scans.apply(lambda row: row['Date of detection CRLM'] <= row['Datum'] <= row['Date of resection CRLM'], axis=1)

In [116]:
all_scans[all_scans['PID Lokaal'] == 1336841]

,Unnamed: 0.1,Unnamed: 0,Identificatienummer patïent,Accessionnummer,PID Lokaal,Datum,Beschrijving,Mod.,# Beelden,BIRADS=0 (10),Tijd,Lichaamsdeel,Status,Subspecialiteit (5),Date of detection CRLM,Date of resection CRLM,Date_In_Range
81,81,81,1336841,4711083.02,1336841,2011-12-29,Herbeoordeling CT abdomen,CT,1,N,20:00:00,ABDO,Gelezen,ABDOMEN,2011-11-14,2012-02-27,True
82,82,82,1336841,4711084.02,1336841,2011-12-29,Herbeoordeling CT abdomen,CT,1,N,20:00:00,ABDO,Gelezen,ABDOMEN,2011-11-14,2012-02-27,True
83,83,83,1336841,4759778.02,1336841,2012-06-13,CT Thorax/abdomen,CT OT,569,N,12:30:00,ABDO,Gelezen,ABDOMEN,2011-11-14,2012-02-27,False
84,84,84,1336841,4821424.02,1336841,2012-12-11,CT Thorax/abdomen,CT,684,N,13:23:48,ABDO,Gelezen,ABDOMEN,2011-11-14,2012-02-27,False

In [144]:
valid_scans = all_scans[all_scans['Date_In_Range'] == True]
filter_scans = valid_scans[valid_scans['PID Lokaal'].isin(ids)]

In [146]:
filter_scans.to_csv("../../New_Extra_Data/filtered_scans.csv",index=False)

In [141]:
filter_ids

,Unnamed: 0.1,Unnamed: 0,Identificatienummer patïent,Accessionnummer,PID Lokaal,Datum,Beschrijving,Mod.,# Beelden,BIRADS=0 (10),Tijd,Lichaamsdeel,Status,Subspecialiteit (5),Date of detection CRLM,Date of resection CRLM,Date_In_Range
33,33,33,1131673,364438.00,1131673,2018-02-20,Herbeoordeling CT thorax abdomen,CT PR,790,N,09:00:30,ABDO,Gelezen,ABDOMEN,2018-02-20,2018-05-22,True
34,34,34,1131673,364442.00,1131673,2018-03-09,Herbeoordeling PET-CT,PT CT PR,2240,N,14:46:22,NUGE,Definitief,NUGE,2018-02-20,2018-05-22,True
35,35,35,1131673,364442.00,1131673,2018-03-09,Herbeoordeling PET-CT,PT OT CT PR,8,N,16:11:16,NUGE,Gelezen,NUGE,2018-02-20,2018-05-22,True
36,36,36,1131673,454501.00,1131673,2018-05-26,CT Nieren urinewegen,CT PR,2791,N,16:01:15,ABDO,Gelezen,ABDOMEN,2018-02-20,2018-05-22,False
37,37,37,1131673,455138.00,1131673,2018-05-28,CT Abdomen met contrast,CT SR,2716,N,10:41:15,ABDO,Gelezen,ABDOMEN,2018-02-20,2018-05-22,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4881,4881,4886,9882025,5219213.02,9882025,2014-04-07,Herbeoordeling CT neuro,CT,1,N,12:30:00,OVRG,Gelezen,NEURO,2014-04-07,2014-06-17,True
4882,4882,4887,9882025,5216547.01,9882025,2014-04-07,PET WB FDG,CT PT SC,5246,N,12:30:00,OVRG,Gelezen,NUGE,2014-04-07,2014-06-17,True
4883,4883,4888,9882025,464642.00,9882025,2018-05-24,Extern onderzoek CT,CT PR,715,N,13:30:18,OVRG,Gelezen,NEURO,2014-04-07,2014-06-17,False
4884,4884,4889,9882025,1910018.00,9882025,2021-05-06,CT Thorax/abdomen,CT SR,1216,NaN,11:35:40,ABDO,Definitief,ABDOMEN,2014-04-07,2014-06-17,False
4885,4885,4890,9882025,2383939.00,9882025,2022-03-02,CT Thorax/abdomen,CT SR,1159,NaN,15:31:43,ABDO,Definitief,ABDOMEN,2014-04-07,2014-06-17,False

In [121]:
sorted(all_scans[all_scans['Date_In_Range']]['PID Lokaal'].unique().tolist())

[64059,
 121369,
 153303,
 192814,
 265994,
 275031,
 292285,
 311642,
 320008,
 330025,
 377631,
 396418,
 410611,
 449829,
 470103,
 472421,
 478665,
 483623,
 509363,
 521867,
 593377,
 611888,
 621065,
 624984,
 637720,
 641944,
 658427,
 692977,
 696567,
 717667,
 741673,
 771262,
 788823,
 797177,
 802551,
 813986,
 874433,
 916866,
 934703,
 969857,
 986474,
 1005675,
 1008882,
 1021464,
 1029276,
 1030425,
 1038772,
 1051480,
 1055209,
 1064567,
 1079460,
 1086001,
 1094923,
 1101607,
 1103853,
 1106100,
 1121221,
 1131673,
 1136985,
 1140146,
 1157284,
 1168627,
 1173298,
 1173628,
 1175502,
 1200640,
 1228328,
 1238629,
 1241838,
 1247656,
 1277577,
 1336841,
 1350847,
 1411345,
 1458543,
 1549681,
 1567015,
 1585735,
 1635950,
 1637698,
 1669121,
 1678496,
 1682949,
 1684409,
 1776761,
 1780834,
 1799268,
 1800150,
 1803305,
 1820221,
 1820851,
 1839348,
 1872150,
 1879739,
 1894206,
 1899657,
 1912328,
 1931976,
 1944042,
 2006537,
 2031039,
 2039162,
 2092096,
 2120972,
 2123264,
 2147587,
 2165861,
 2166110,
 2191785,
 2251379,
 2469868,
 2489453,
 2550583,
 2565701,
 2590444,
 2620776,
 2724050,
 2752471,
 2774723,
 2805049,
 2927089,
 2972809,
 2995387,
 3015244,
 3027974,
 3053109,
 3092569,
 3097015,
 3105859,
 3187937,
 3227315,
 3289107,
 3295695,
 3322734,
 3346249,
 3388949,
 3395561,
 3423895,
 3429629,
 3470671,
 3497959,
 3557743,
 3562064,
 3563254,
 3610925,
 3679693,
 3799902,
 3801275,
 3827045,
 3828190,
 3835063,
 3835842,
 3857156,
 3878243,
 3892587,
 3913348,
 3915119,
 3921959,
 3929138,
 3932332,
 3953745,
 3985131,
 3999071,
 4033021,
 4062798,
 4107704,
 4123507,
 4174259,
 4218251,
 4267801,
 4302527,
 4327749,
 4335562,
 4344349,
 4346065,
 4358305,
 4363433,
 4391369,
 4426829,
 4445236,
 4466776,
 4493539,
 4557139,
 4560823,
 4577253,
 4723543,
 4759717,
 4778100,
 4778949,
 4793625,
 4796367,
 4798055,
 4876374,
 4892516,
 4893397,
 4895656,
 4932909,
 4978701,
 5002654,
 5037539,
 5048420,
 5050447,
 5071314,
 5074135,
 5088272,
 5118749,
 5120470,
 5130984,
 5137177,
 5155211,
 5157798,
 5253957,
 5321235,
 5325761,
 5422229,
 5489131,
 5540147,
 5562239,
 5613344,
 5628609,
 5662641,
 5707669,
 5742910,
 5796551,
 5800783,
 5811138,
 5855711,
 5865145,
 5870261,
 5879354,
 5905584,
 5978471,
 5985242,
 5988641,
 6011357,
 6019571,
 6023209,
 6088648,
 6109656,
 6170669,
 6190781,
 6263669,
 6274929,
 6289359,
 6359664,
 6370665,
 6387510,
 6389799,
 6396525,
 6403628,
 6431015,
 6455598,
 6472999,
 6477158,
 6493449,
 6504998,
 6522123,
 6562966,
 6606919,
 6643893,
 6674661,
 6676629,
 6684059,
 6688472,
 6720709,
 6746373,
 6796557,
 6801007,
 6811238,
 6818250,
 6823155,
 6828898,
 6856821,
 6863085,
 6868155,
 6874007,
 6876775,
 6927879,
 6932403,
 6965358,
 6970920,
 7029795,
 7104185,
 7118545,
 7152829,
 7157188,
 7195572,
 7232950,
 7285747,
 7324357,
 7326641,
 7327180,
 7393330,
 7416593,
 7451650,
 7465191,
 7521047,
 7552451,
 7591120,
 7618938,
 7625295,
 7648607,
 7652278,
 7662366,
 7693913,
 7777608,
 7819729,
 7845187,
 7855374,
 7860009,
 7863118,
 7904521,
 7946652,
 7958711,
 7959057,
 7990698,
 7992998,
 8035619,
 8037018,
 8065953,
 8084101,
 8102169,
 8112397,
 8128849,
 8186111,
 8202397,
 8205683,
 8211531,
 8264863,
 8281659,
 8315491,
 8325505,
 8351336,
 8361586,
 8386341,
 8408989,
 8416957,
 8488669,
 8529499,
 8578584,
 8609771,
 8634467,
 8660570,
 8690842,
 8791531,
 8805017,
 8836161,
 8859793,
 8894270,
 8910704,
 8928206,
 8955369,
 9003021,
 9032247,
 9036978,
 9055421,
 9087307,
 9103066,
 9114187,
 9129907,
 9147114,
 9149064,
 9152120,
 9166873,
 9172042,
 9176243,
 9203144,
 9204566,
 9247015,
 9278300,
 9304163,
 9311555,
 9335489,
 9353075,
 9353499,
 9356155,
 9373725,
 9414259,
 9429525,
 9530658,
 9534200,
 9557141,
 9691176,
 9731939,
 9759331,
 9801055,
 9803729,
 9863363,
 9872828,
 9876815,
 9882025,
 9913446,
 9926135,
 9928848]

In [68]:
df_2['ID']

0      1336841
1      1336841
2      1336841
3      1336841
4      5088272
        ...
102    3497959
103    3497959
104    3497959
105    1055209
106     410611
Name: ID, Length: 107, dtype: int64

In [8]:
date_format = "%d.%m.%Y"

possible_missing_patients = all_patients[all_patients["PID"].isin(possible_missing_patients_id)]

#如果scan data的Date在 detection和resection之间，那么就是有用的
missing_patients_scans = {id:[] for id in possible_missing_patients_id}
for id in possible_missing_patients_id:
    all_dates = all_scans[all_scans["PID Lokaal"]==id]["Datum"].tolist()
    detection_date = possible_missing_patients[possible_missing_patients["PID"]==id]["Date of detection CRLM"]
    resection_date = possible_missing_patients[possible_missing_patients["PID"]==id]["Date of resection CRLM"]

    detection_date = datetime.strptime(detection_date.values[0],date_format)
    resection_date = datetime.strptime(resection_date.values[0],date_format)
    for date in all_dates:
        
        if date >= detection_date and date <= resection_date:

            missing_patients_scans[id].append(date)

In [9]:
missing_patients_acc_num= {id:[] for id in possible_missing_patients_id}

In [10]:
import pandas as pd

# Your data


# Converting to a DataFrame
# We will create a list of tuples where each tuple contains an ID and a timestamp
# If an ID has no timestamps, it will not appear in the DataFrame

rows = []
for id, timestamps in missing_patients_scans.items():
    if timestamps:  # Check if the list of timestamps is not empty
        for timestamp in timestamps:
            rows.append((id, timestamp))

# Creating the DataFrame
df = pd.DataFrame(rows, columns=['ID', 'Timestamp'])

# Display the DataFrame
df


count = 0
for id,date in missing_patients_scans.items():
    if date:
        for one_date in date:
            acc_num = (all_scans.loc[(all_scans["PID Lokaal"]==id) & (all_scans["Datum"]==one_date)]['Accessionnummer'].values)
            missing_patients_acc_num[id].append(acc_num)

In [11]:
missing_patients_acc_num

{1336841: [array([4711083.02, 4711084.02]), array([4711083.02, 4711084.02])],
 592396: [],
 9740304: [],
 5088272: [array([2921658.01]), array([2996302.01]), array([2998820.01])],
 3289107: [array([2894686.01]),
  array([2898330.01]),
  array([2938284.01]),
  array([2966271.01])],
 9796117: [],
 5685277: [],
 1555490: [],
 9610788: [],
 6389799: [array([5075187.02])],
 6023209: [array([527981.])],
 6401582: [],
 4445236: [array([2871433.01]), array([2876826.01])],
 1406520: [],
 9950266: [],
 8281659: [array([4195770.02])],
 64059: [array([3663786.01])],
 2565701: [array([3081690.01])],
 9172042: [array([4135229.02])],
 1805389: [],
 4062798: [array([4768193.02])],
 9287247: [],
 7313488: [],
 3647570: [],
 1780834: [array([3142787.01])],
 5409893: [],
 1984111: [],
 8361586: [array([4395941.02])],
 1064567: [array([165002.])],
 3759223: [],
 7913597: [],
 7293054: [],
 3006080: [],
 3896453: [],
 9149064: [array([3002116.01])],
 8191112: [],
 1932428: [],
 3775630: [],
 8805017: [array([3026132.01])],
 1131673: [array([364438.]),
  array([364442., 364442.]),
  array([364442., 364442.])],
 8690842: [array([2931559.01])],
 1808540: [],
 1029276: [array([88028.])],
 4624025: [],
 9594015: [],
 1157284: [array([436187.])],
 4759717: [array([2901781.01])],
 3835063: [array([5733759.02])],
 3801275: [array([3010416.01])],
 8744124: [],
 2426559: [],
 2774723: [array([565381., 565064.]), array([565381., 565064.])],
 8626379: [],
 4025551: [],
 7591120: [array([4025032.02])],
 4346065: [array([4344000.02, 4344000.02]),
  array([4344000.02, 4344000.02]),
  array([4344000.02, 4344006.02]),
  array([4344000.02, 4344006.02])],
 7118545: [array([4011956.02])],
 2378963: [],
 4028119: [],
 7717084: [],
 2312416: [],
 9207011: [],
 5130984: [array([4727025.02]), array([4727025.02])],
 2590444: [array([4117055.02])],
 8757487: [],
 1168627: [array([473935.]), array([473936.])],
 1839348: [array([5598520.02])],
 308469: [],
 3558645: [],
 1889015: [],
 8714490: [],
 2863869: [],
 7358214: [],
 7035143: [],
 6493449: [array([411713.])],
 265994: [array([4202379.02])],
 7416593: [array([40930.])],
 1872150: [array([150833.])],
 8102169: [array([427789.])],
 4267801: [array([3014553.01])],
 7917339: [],
 377631: [array([4413134.02])],
 6772005: [],
 102184: [],
 7734058: [],
 2503978: [],
 4794159: [],
 1173298: [array([490592.])],
 6387510: [array([4449697.02])],
 2550583: [array([2998800.01]), array([3026123.01])],
 2805049: [array([3021769.01])],
 6786873: [],
 1409855: [],
 7777608: [array([4236633.02])],
 1850700: [],
 7438669: [],
 4723543: [array([5179292.02]), array([5180030.02])],
 5589336: [],
 7941466: [],
 7648607: [array([4182311.02])],
 5757286: [],
 4351846: [],
 5601641: [],
 986474: [array([3569718.01])],
 1977197: [],
 8910704: [array([5604789.02])],
 4878193: [],
 6274929: [array([3023111.01]), array([3029041.01])],
 9353075: [array([3817321.02])],
 8447353: [],
 2695552: [],
 1111937: [],
 739718: [],
 6943627: [],
 1941390: [],
 3574163: [],
 5860245: [],
 5002654: [array([3601687.01])],
 5157798: [array([4189504.02])],
 9882025: [array([5219213.02, 5216547.01]), array([5219213.02, 5216547.01])],
 731563: [],
 9129907: [array([3833891.02])],
 5504948: [],
 2773429: [],
 7652278: [array([4728601.02]), array([4735043.02])],
 8902078: [],
 2909632: [],
 5325761: [array([239205.])],
 4391369: [array([4667076.02])],
 7327180: [array([4326556.02])],
 3679693: [array([3009610.01])],
 3295695: [array([4226479.02])],
 4796367: [array([3024267.01])],
 7819729: [array([3061180.01])],
 5071314: [array([3771171.02])],
 8623057: [],
 8938961: [],
 302547: [],
 4206038: [],
 2752471: [array([2957539.01]), array([2988403.01]), array([3006140.01])],
 4875737: [],
 6042077: [],
 3828190: [array([5957765.02, 5954994.01]), array([5957765.02, 5954994.01])],
 6815197: [],
 8316381: [],
 3250147: [],
 3497959: [array([643824., 624716.]), array([643824., 624716.])],
 1055209: [array([148802.])],
 6394347: [],
 5075435: [],
 7791599: [],
 410611: [array([4016380.02])],
 39927: [],
 1236985: [],
 8382972: [],
 9413117: []}

In [12]:
for id,acc_num in missing_patients_acc_num.items():
    missing_patients_acc_num[id] = [array[i] for array in acc_num for i in range(len(array)) ]

In [13]:
missing_patients_acc_num

{1336841: [4711083.02, 4711084.02, 4711083.02, 4711084.02],
 592396: [],
 9740304: [],
 5088272: [2921658.01, 2996302.01, 2998820.01],
 3289107: [2894686.01, 2898330.01, 2938284.01, 2966271.01],
 9796117: [],
 5685277: [],
 1555490: [],
 9610788: [],
 6389799: [5075187.02],
 6023209: [527981.0],
 6401582: [],
 4445236: [2871433.01, 2876826.01],
 1406520: [],
 9950266: [],
 8281659: [4195770.02],
 64059: [3663786.01],
 2565701: [3081690.01],
 9172042: [4135229.02],
 1805389: [],
 4062798: [4768193.02],
 9287247: [],
 7313488: [],
 3647570: [],
 1780834: [3142787.01],
 5409893: [],
 1984111: [],
 8361586: [4395941.02],
 1064567: [165002.0],
 3759223: [],
 7913597: [],
 7293054: [],
 3006080: [],
 3896453: [],
 9149064: [3002116.01],
 8191112: [],
 1932428: [],
 3775630: [],
 8805017: [3026132.01],
 1131673: [364438.0, 364442.0, 364442.0, 364442.0, 364442.0],
 8690842: [2931559.01],
 1808540: [],
 1029276: [88028.0],
 4624025: [],
 9594015: [],
 1157284: [436187.0],
 4759717: [2901781.01],
 3835063: [5733759.02],
 3801275: [3010416.01],
 8744124: [],
 2426559: [],
 2774723: [565381.0, 565064.0, 565381.0, 565064.0],
 8626379: [],
 4025551: [],
 7591120: [4025032.02],
 4346065: [4344000.02,
  4344000.02,
  4344000.02,
  4344000.02,
  4344000.02,
  4344006.02,
  4344000.02,
  4344006.02],
 7118545: [4011956.02],
 2378963: [],
 4028119: [],
 7717084: [],
 2312416: [],
 9207011: [],
 5130984: [4727025.02, 4727025.02],
 2590444: [4117055.02],
 8757487: [],
 1168627: [473935.0, 473936.0],
 1839348: [5598520.02],
 308469: [],
 3558645: [],
 1889015: [],
 8714490: [],
 2863869: [],
 7358214: [],
 7035143: [],
 6493449: [411713.0],
 265994: [4202379.02],
 7416593: [40930.0],
 1872150: [150833.0],
 8102169: [427789.0],
 4267801: [3014553.01],
 7917339: [],
 377631: [4413134.02],
 6772005: [],
 102184: [],
 7734058: [],
 2503978: [],
 4794159: [],
 1173298: [490592.0],
 6387510: [4449697.02],
 2550583: [2998800.01, 3026123.01],
 2805049: [3021769.01],
 6786873: [],
 1409855: [],
 7777608: [4236633.02],
 1850700: [],
 7438669: [],
 4723543: [5179292.02, 5180030.02],
 5589336: [],
 7941466: [],
 7648607: [4182311.02],
 5757286: [],
 4351846: [],
 5601641: [],
 986474: [3569718.01],
 1977197: [],
 8910704: [5604789.02],
 4878193: [],
 6274929: [3023111.01, 3029041.01],
 9353075: [3817321.02],
 8447353: [],
 2695552: [],
 1111937: [],
 739718: [],
 6943627: [],
 1941390: [],
 3574163: [],
 5860245: [],
 5002654: [3601687.01],
 5157798: [4189504.02],
 9882025: [5219213.02, 5216547.01, 5219213.02, 5216547.01],
 731563: [],
 9129907: [3833891.02],
 5504948: [],
 2773429: [],
 7652278: [4728601.02, 4735043.02],
 8902078: [],
 2909632: [],
 5325761: [239205.0],
 4391369: [4667076.02],
 7327180: [4326556.02],
 3679693: [3009610.01],
 3295695: [4226479.02],
 4796367: [3024267.01],
 7819729: [3061180.01],
 5071314: [3771171.02],
 8623057: [],
 8938961: [],
 302547: [],
 4206038: [],
 2752471: [2957539.01, 2988403.01, 3006140.01],
 4875737: [],
 6042077: [],
 3828190: [5957765.02, 5954994.01, 5957765.02, 5954994.01],
 6815197: [],
 8316381: [],
 3250147: [],
 3497959: [643824.0, 624716.0, 643824.0, 624716.0],
 1055209: [148802.0],
 6394347: [],
 5075435: [],
 7791599: [],
 410611: [4016380.02],
 39927: [],
 1236985: [],
 8382972: [],
 9413117: []}

In [14]:

rows = []
for id, timestamps in missing_patients_acc_num.items():
    if timestamps:  # Check if the list of timestamps is not empty
        for timestamp in timestamps:
            rows.append((id, timestamp))

# Creating the DataFrame
df_2= pd.DataFrame(rows, columns=['ID', 'Accessionnummer'])

# Display the DataFrame
df['Accessionnummer'] = df_2['Accessionnummer']

In [24]:
df_2

          ID  Accessionnummer
0    1336841       4711083.02
1    1336841       4711084.02
2    1336841       4711083.02
3    1336841       4711084.02
4    5088272       2921658.01
..       ...              ...
102  3497959        624716.00
103  3497959        643824.00
104  3497959        624716.00
105  1055209        148802.00
106   410611       4016380.02

[107 rows x 2 columns]

In [18]:
df[df['ID'] == 4445236]

         ID  Timestamp  Accessionnummer
11  4445236 2002-09-23       5075187.02
12  4445236 2002-10-18        527981.00

In [415]:
df.to_csv("missing_patients.csv",index=False)

In [376]:
timestamp = pd.Timestamp('2011-12-29 00:00:00')

In [378]:
df['Timestamp'] = df['Timestamp'].apply(lambda x:  x.strftime('%Y-%m-%d'))

In [382]:
df.to_csv("missing_patients.csv",index=False)

In [385]:
all_scans.loc[all_scans['Identificatienummer patïent']==9882025]

,Unnamed: 0.1,Unnamed: 0,Identificatienummer patïent,Accessionnummer,PID Lokaal,Datum,Beschrijving,Mod.,# Beelden,BIRADS=0 (10),Tijd,Lichaamsdeel,Status,Subspecialiteit (5),Date of detection CRLM,Date of resection CRLM
4878,4878,4883,9882025,4463713.02,9882025,2010-12-02,CT Abdomen met contrast,CT,146,N,09:30:00,ABDO,Gelezen,ABDOMEN,07.04.2014,17.06.2014
4879,4879,4884,9882025,5159094.02,9882025,2014-01-03,Herbeoordeling CT neuro,CT,1,N,09:30:00,OVRG,Gelezen,NEURO,07.04.2014,17.06.2014
4880,4880,4885,9882025,5158584.01,9882025,2014-01-03,PET^CT_WB_Long_Erasmus (Adult),CT PT SC,2956,N,11:16:19,OVRG,Gelezen,NUGE,07.04.2014,17.06.2014
4881,4881,4886,9882025,5219213.02,9882025,2014-04-07,Herbeoordeling CT neuro,CT,1,N,12:30:00,OVRG,Gelezen,NEURO,07.04.2014,17.06.2014
4882,4882,4887,9882025,5216547.01,9882025,2014-04-07,PET WB FDG,CT PT SC,5246,N,12:30:00,OVRG,Gelezen,NUGE,07.04.2014,17.06.2014
4883,4883,4888,9882025,464642.00,9882025,2018-05-24,Extern onderzoek CT,CT PR,715,N,13:30:18,OVRG,Gelezen,NEURO,07.04.2014,17.06.2014
4884,4884,4889,9882025,1910018.00,9882025,2021-05-06,CT Thorax/abdomen,CT SR,1216,NaN,11:35:40,ABDO,Definitief,ABDOMEN,07.04.2014,17.06.2014
4885,4885,4890,9882025,2383939.00,9882025,2022-03-02,CT Thorax/abdomen,CT SR,1159,NaN,15:31:43,ABDO,Definitief,ABDOMEN,07.04.2014,17.06.2014

In [464]:
missing_data = pd.read_csv('../../New_Extra_Data/missing_patients.csv')
#
missing_data = missing_data.sort_values(by=['ID']).reset_index(drop=True)
#add Anon ID
missing_data['Anon ID'] = None

In [465]:
initi_value = 342
pre_index = missing_data['ID'].values[0]
for index,row in missing_data.iterrows():
    if row['ID'] == pre_index:
        row['Anon ID'] = "CRLM_" + str(initi_value)
    else:
        initi_value += 1
        row['Anon ID'] = "CRLM_" + str(initi_value)
    pre_index = row['ID']
    missing_data.iloc[index,3] = row['Anon ID']

In [467]:

missing_data.to_csv("../../New_Extra_Data/missing_patients.csv",index=False)

In [474]:
#get missing patients without appropriate scan
missing_patients_no_valid_scan = []
for id in missing_patients_scans.keys():
    if not missing_patients_acc_num[id]:
        missing_patients_no_valid_scan.append(id)

In [476]:
pd.DataFrame(missing_patients_no_valid_scan).to_csv("../../New_Extra_Data/missing_patients_no_valid_scan.csv",index=False)

In [479]:
pd.DataFrame(missing_patients_id_no_scan).to_csv("../../New_Extra_Data/missing_patients_no_scan.csv",index=False)

In [478]:
156-89

67

        PID  Anon ID  Date Scan   Accession nr.
9    265994      NaN  23.07.2009     4202379.02
5    377631      NaN  08.09.2010     4413134.02
12   410611      NaN  23.10.2008     4016380.02
6   1029276      NaN  21.08.2017       88028.00
10  1055209      NaN  29.09.2017      148802.00
..      ...      ...         ...            ...
75  9149064      NaN  31.07.2003     3002116.01
78  9172042      NaN  12.05.2009     4135229.02
79  9353075      NaN  15.11.2007     3817321.02
82  9882025      NaN  07.04.2014     5219213.02
83  9882025      NaN  07.04.2014     5216547.01

[84 rows x 4 columns]